name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v2
        id: cache-cabal
        name: Cache dependencies
        with:
          path: |
            ~/.cabal/config
            ~/.cabal/packages/hackage.haskell.org/
            ~/.cabal/store
          key: ${{ runner.os }}-latest-cabal-${{ hashFiles('cabal.project') }}
          restore-keys: ${{ runner.os }}-latest-cabal-

      - uses: actions/cache@v2
        name: Cache build
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-latest-dist-${{ github.sha }}
          restore-keys: ${{ runner.os }}-latest-dist-

      - name: cabal update
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        run: cabal update

      - name: cabal build
        run: cabal build --disable-optimization
