name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v2
        id: cache-ghc
        name: Cache GHC
        with:
          path: ~/.ghcup/*
          key: ${{ runner.os }}-0-ghcup-${{ hashFiles('./ci/install.sh') }}

      - uses: actions/cache@v2
        id: cache-cabal
        name: Cache dependencies
        with:
          path: |
            ~/.cabal/config
            ~/.cabal/packages/hackage.haskell.org/
            ~/.cabal/store
          key: ${{ runner.os }}-0-cabal-${{ github.sha }}
          restore-keys: ${{ runner.os }}-0-cabal-

      - name: Install ghc
        if: steps.cache-ghc.outputs.cache-hit != 'true'
        run: ./ci/install.sh

      - name: Add ~/.ghcup/bin to path
        run: echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

      - name: Cabal update
        run: cabal update

      - name: Build
        run: ./ci/build.sh
